//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F_e_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageAddress {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageAddress() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F_e_Resources.PageAddress", typeof(PageAddress).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Admin/Categories/Delete.
        /// </summary>
        public static string AdminCategoryDelete {
            get {
                return ResourceManager.GetString("AdminCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Admin/Categories/Edit.
        /// </summary>
        public static string AdminCategoryEdit {
            get {
                return ResourceManager.GetString("AdminCategoryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Admin/Categories/Index.
        /// </summary>
        public static string AdminCategoryMain {
            get {
                return ResourceManager.GetString("AdminCategoryMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Admin/FoodTypes/Delete.
        /// </summary>
        public static string AdminFoodDelete {
            get {
                return ResourceManager.GetString("AdminFoodDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Admin/FoodTypes/Edit.
        /// </summary>
        public static string AdminFoodEdit {
            get {
                return ResourceManager.GetString("AdminFoodEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Admin/FoodTypes/Index.
        /// </summary>
        public static string AdminFoodMain {
            get {
                return ResourceManager.GetString("AdminFoodMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Index.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Privacy.
        /// </summary>
        public static string MainPrivacy {
            get {
                return ResourceManager.GetString("MainPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Admin/MenuItems/Index.
        /// </summary>
        public static string MenuItemManagement {
            get {
                return ResourceManager.GetString("MenuItemManagement", resourceCulture);
            }
        }
    }
}
